# Autogenerated by "rake mappings:formatters". Everytime you edit
# a builtin formatter definition run "rake mappings:lexers" to
# update the cache.
#
# Do not alter FORMATTERS_CACHE manually!

module Rugments
  FORMATTERS_CACHE = {:terminal256=>
  {:class_name=>"Rugments::Formatters::Terminal256",
   :source_file=>"formatters/terminal256.rb"},
 :html=>
  {:class_name=>"Rugments::Formatters::HTML",
   :source_file=>"formatters/html.rb"},
 :null=>
  {:class_name=>"Rugments::Formatters::Null",
   :source_file=>"formatters/null.rb"}}
end
