# Autogenerated by "rake mappings:themes". Everytime you edit
# a builtin formatter definition run "rake mappings:themes" to
# update the cache.
#
# Do not alter THEMES_CACHE manually!

module Rugments
  THEMES_CACHE = {:github=>{:class_name=>"github", :source_file=>"themes/github.rb"},
 :colorful=>{:class_name=>"colorful", :source_file=>"themes/colorful.rb"},
 :base16=>{:class_name=>"base16", :source_file=>"themes/base16.rb"},
 :monokai=>{:class_name=>"monokai", :source_file=>"themes/monokai.rb"},
 :thankful_eyes=>
  {:class_name=>"thankful_eyes", :source_file=>"themes/thankful_eyes.rb"},
 :"monokai.sublime"=>
  {:class_name=>"monokai.sublime", :source_file=>"themes/monokai.sublime.rb"}}
end
